# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ht.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        font = QtGui.QFont()
        font.setFamily("Piboto [Goog]")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.dateTimeC1 = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeC1.setGeometry(QtCore.QRect(180, 70, 194, 32))
        self.dateTimeC1.setMinimumDate(QtCore.QDate(2021, 1, 1))
        self.dateTimeC1.setCalendarPopup(True)
        self.dateTimeC1.setObjectName("dateTimeC1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.dateTimeC2 = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeC2.setGeometry(QtCore.QRect(180, 140, 194, 32))
        self.dateTimeC2.setMinimumDate(QtCore.QDate(2021, 1, 1))
        self.dateTimeC2.setCalendarPopup(True)
        self.dateTimeC2.setObjectName("dateTimeC2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.dateTimeC3 = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeC3.setGeometry(QtCore.QRect(180, 210, 194, 32))
        self.dateTimeC3.setMinimumDate(QtCore.QDate(2021, 1, 1))
        self.dateTimeC3.setCalendarPopup(True)
        self.dateTimeC3.setObjectName("dateTimeC3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(420, 70, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(420, 210, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.dateTimeC5 = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeC5.setGeometry(QtCore.QRect(590, 140, 194, 32))
        self.dateTimeC5.setMinimumDate(QtCore.QDate(2021, 1, 1))
        self.dateTimeC5.setCalendarPopup(True)
        self.dateTimeC5.setObjectName("dateTimeC5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(420, 140, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.dateTimeC4 = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeC4.setGeometry(QtCore.QRect(590, 70, 194, 32))
        self.dateTimeC4.setMinimumDate(QtCore.QDate(2021, 1, 1))
        self.dateTimeC4.setCalendarPopup(True)
        self.dateTimeC4.setObjectName("dateTimeC4")
        self.dateTimeC6 = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeC6.setGeometry(QtCore.QRect(590, 210, 194, 32))
        self.dateTimeC6.setMinimumDate(QtCore.QDate(2021, 1, 1))
        self.dateTimeC6.setCalendarPopup(True)
        self.dateTimeC6.setObjectName("dateTimeC6")
        self.B_Save = QtWidgets.QPushButton(self.centralwidget)
        self.B_Save.setGeometry(QtCore.QRect(340, 290, 99, 30))
        self.B_Save.setObjectName("B_Save")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(390, 70, 20, 171))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(170, 350, 391, 31))
        self.label_8.setObjectName("label_8")
        self.B_Home = QtWidgets.QPushButton(self.centralwidget)
        self.B_Home.setGeometry(QtCore.QRect(750, 0, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Tibetan")
        self.B_Home.setFont(font)
        self.B_Home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IMG/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.B_Home.setIcon(icon)
        self.B_Home.setIconSize(QtCore.QSize(40, 40))
        self.B_Home.setObjectName("B_Home")
        self.label.raise_()
        self.label_2.raise_()
        self.dateTimeC1.raise_()
        self.label_3.raise_()
        self.dateTimeC2.raise_()
        self.label_4.raise_()
        self.dateTimeC3.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.dateTimeC5.raise_()
        self.label_7.raise_()
        self.dateTimeC6.raise_()
        self.B_Save.raise_()
        self.line.raise_()
        self.label_8.raise_()
        self.B_Home.raise_()
        self.dateTimeC4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.dateTimeC1, self.dateTimeC2)
        MainWindow.setTabOrder(self.dateTimeC2, self.dateTimeC3)
        MainWindow.setTabOrder(self.dateTimeC3, self.dateTimeC5)
        MainWindow.setTabOrder(self.dateTimeC5, self.dateTimeC4)
        MainWindow.setTabOrder(self.dateTimeC4, self.dateTimeC6)
        MainWindow.setTabOrder(self.dateTimeC6, self.B_Save)
        MainWindow.setTabOrder(self.B_Save, self.B_Home)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "HORARIO DE TOMA "))
        self.label_2.setText(_translate("MainWindow", "Compartimiento 1"))
        self.label_3.setText(_translate("MainWindow", "Compartimiento 2"))
        self.label_4.setText(_translate("MainWindow", "Compartimiento 3"))
        self.label_5.setText(_translate("MainWindow", "Compartimiento 4"))
        self.label_6.setText(_translate("MainWindow", "Compartimiento 6"))
        self.label_7.setText(_translate("MainWindow", "Compartimiento 5"))
        self.B_Save.setText(_translate("MainWindow", "Guardar"))
        self.label_8.setText(_translate("MainWindow", "Recuerda: El compartimiento 7 debe permanecer vacio"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

