# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Inicio.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate, QTime, QDateTime, Qt, QThread, QCoreApplication



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("IMG/cielo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.B_Emg = QtWidgets.QPushButton(self.centralwidget)
        self.B_Emg.setGeometry(QtCore.QRect(180, 140, 100, 100))
        self.B_Emg.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IMG/emergency-call.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.B_Emg.setIcon(icon)
        self.B_Emg.setIconSize(QtCore.QSize(80, 80))
        self.B_Emg.setObjectName("B_Emg")
        self.B_Pill = QtWidgets.QPushButton(self.centralwidget)
        self.B_Pill.setGeometry(QtCore.QRect(420, 140, 100, 100))
        self.B_Pill.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("IMG/medicine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.B_Pill.setIcon(icon1)
        self.B_Pill.setIconSize(QtCore.QSize(80, 80))
        self.B_Pill.setObjectName("B_Pill")
        self.B_Photo = QtWidgets.QPushButton(self.centralwidget)
        self.B_Photo.setGeometry(QtCore.QRect(70, 300, 100, 100))
        self.B_Photo.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("IMG/gallery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.B_Photo.setIcon(icon2)
        self.B_Photo.setIconSize(QtCore.QSize(80, 80))
        self.B_Photo.setObjectName("B_Photo")
        self.B_Games = QtWidgets.QPushButton(self.centralwidget)
        self.B_Games.setGeometry(QtCore.QRect(300, 300, 100, 100))
        self.B_Games.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("IMG/dado.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.B_Games.setIcon(icon3)
        self.B_Games.setIconSize(QtCore.QSize(80, 80))
        self.B_Games.setObjectName("B_Games")
        self.B_Music = QtWidgets.QPushButton(self.centralwidget)
        self.B_Music.setGeometry(QtCore.QRect(530, 300, 100, 100))
        self.B_Music.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("IMG/music.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.B_Music.setIcon(icon4)
        self.B_Music.setIconSize(QtCore.QSize(80, 80))
        self.B_Music.setObjectName("B_Music")
        self.B_Settings = QtWidgets.QPushButton(self.centralwidget)
        self.B_Settings.setGeometry(QtCore.QRect(660, 0, 50, 50))
        self.B_Settings.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("IMG/technical-support.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.B_Settings.setIcon(icon5)
        self.B_Settings.setIconSize(QtCore.QSize(40, 40))
        self.B_Settings.setObjectName("B_Settings")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 110, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(400, 110, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(90, 270, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(320, 270, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(540, 270, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "HOY ES :"+ QDateTime.currentDate()))
        self.label_3.setText(_translate("MainWindow", "LA HORA ES:"))
        self.label_4.setText(_translate("MainWindow", "EMERGENCIA"))
        self.label_5.setText(_translate("MainWindow", "HORARIO DE TOMAS "))
        self.label_6.setText(_translate("MainWindow", "FOTOS"))
        self.label_7.setText(_translate("MainWindow", "JUEGOS"))
        self.label_8.setText(_translate("MainWindow", "MUSICA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

